import course1 from "../../assets/image/course-img1.jpg";
import course2 from "../../assets/image/course-img2.jpg";
import course3 from "../../assets/image/course-img3.jpg";
import course4 from "../../assets/image/course-img4.jpg";

const productData = [
  {
    id: 1,
    ispaid: true,
    name: "Membuat 3D Modelling Menggunakan Blender",
    mentor: "Gilang Pratama",
    image: course1,
    deskripsi:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.",
    sesi1: "pengenalan",
    sesi2: "pendalaman",
    sesi3: "latihan",
    sesi4: "penerapan",
    sesi5: "test",
    date: "Kamis, 8 Febuari 2023",
    price: 500000,
    rating: "5",
    category: "Desain",
    label: "Akan Datang",
    jenis: "Kursus",
    rekomendasi: "Rekomendasi",
  },
  {
    id: 2,
    ispaid: true,
    name: "Membuat Animasi 2 Dimensi ",
    mentor: "Gilang Pratama",
    image: course1,
    deskripsi:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.",
    sesi1: "pengenalan",
    sesi2: "pendalaman",
    sesi3: "latihan",
    sesi4: "penerapan",
    sesi5: "test",
    date: "Kamis, 8 Febuari 2023",
    price: 400000,
    rating: 5,
    category: "Animasi",
    label: "Akan Datang",
    jenis: "Kursus",
    rekomendasi: "Rekomendasi",
  },
  {
    id: 3,
    ispaid: true,
    name: "Visual Novel Game Coding",
    mentor: "Gilang Pratama",
    image: course1,
    deskripsi:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.",
    sesi1: "pengenalan",
    sesi2: "pendalaman",
    sesi3: "latihan",
    sesi4: "penerapan",
    sesi5: "test",
    date: "Kamis, 8 Febuari 2023",
    price: 500000,
    rating: 5,
    category: "User Interface",
    label: "Akan Datang",
    jenis: "Kursus",
    rekomendasi: "Rekomendasi",
  },
  {
    id: 4,
    ispaid: true,
    name: "AR/VR Media EducationS",
    mentor: "Gilang Pratama",
    image: course1,
    deskripsi:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.",
    sesi1: "pengenalan",
    sesi2: "pendalaman",
    sesi3: "latihan",
    sesi4: "penerapan",
    sesi5: "test",
    date: "Kamis, 8 Febuari 2023",
    price: 350000,
    rating: 5,
    category: "User Interface",
    label: "Akan Datang",
    jenis: "Kursus",
    rekomendasi: "Rekomendasi",
  },
  {
    id: 5,
    ispaid: false,
    name: "Membuat 3D Modelling Menggunakan Blender",
    mentor: "Gilang Pratama",
    image: course2,
    deskripsi:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.",
    sesi1: "pengenalan",
    sesi2: "pendalaman",
    sesi3: "latihan",
    sesi4: "penerapan",
    sesi5: "test",
    date: "Kamis, 8 Febuari 2023",
    rating: 5,
    category: "Animasi",
    label: "Free",
    jenis: "Kursus",
  },
  {
    id: 6,
    ispaid: false,
    name: "Animasi 2 Dimensi Menggunakan OpenToonz",
    mentor: "Gilang Pratama",
    image: course2,
    deskripsi:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.",
    sesi1: "pengenalan",
    sesi2: "pendalaman",
    sesi3: "latihan",
    sesi4: "penerapan",
    sesi5: "test",
    date: "Kamis, 8 Febuari 2023",
    rating: 5,
    category: "Desain",
    label: "Free",
    jenis: "Kursus",
  },
  {
    id: 7,
    ispaid: false,
    name: "Visual Novel Game Coding",
    mentor: "Gilang Pratama",
    image: course2,
    deskripsi:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.",
    sesi1: "pengenalan",
    sesi2: "pendalaman",
    sesi3: "latihan",
    sesi4: "penerapan",
    sesi5: "test",
    date: "Kamis, 8 Febuari 2023",
    rating: 5,
    category: "Fashion",
    label: "Free",
    jenis: "Kursus",
  },
  {
    id: 8,
    name: "AR/VR Media EducationS",
    mentor: "Gilang Pratama",
    image: course2,
    deskripsi:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.",
    sesi1: "pengenalan",
    sesi2: "pendalaman",
    sesi3: "latihan",
    sesi4: "penerapan",
    sesi5: "test",
    date: "Kamis, 8 Febuari 2023",
    rating: 5,
    category: "Desain",
    label: "Free",
    jenis: "Kursus",
  },
];
export default productData;
